org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 --add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
org.gradle.caching=true
org.gradle.parallel=true
android.javaCompileOptions.jvmTarget=17
# Disable auto toolchain resolution
org.gradle.toolchains.auto-detect=false
android.overridePathCheck=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
